---
title: 'Ch 07: Concept 02'
output: github_document
---


# Autoencoder with images

Import the autoencoder class we wrote earlier:

```{r, results=FALSE}
library(knitr)
library(reticulate)
filenm <- purl("Concept01_autoencoder.Rmd")

source(filenm)
```



```{r}
pickle <- import('pickle')
py <- import_builtins()


unpickle <- function(file){
    fo <- py$open(file, 'rb')
    dict <- pickle$load(fo, encoding='latin1')
    fo$close()
    return(dict)
}


grayscale <- function(a){
  imgs <- aperm(array(t(data), dim = c(32, 32,3,nrow(data))), perm=c(4,3,2,1))
  grayscale_imgs <- apply(imgs, c(1,3,4), mean)
  grayscale_imgs_w<- apply(grayscale_imgs, c(1), function(x){x})
  return(t(apply(grayscale_imgs_w, 2,rev)))
}

```



Download the CIFAR-10 dataset in Python from https://www.cs.toronto.edu/~kriz/cifar.html. Then we can load the data using the following code:


```{r, cache=T}

names <- unpickle(paste0("cifar-10-batches-py","/","batches.meta"))$label_names

filenames <- list.files("cifar-10-batches-py",pattern = "data_batch",full.names = T)
batch_data <- lapply(filenames, unpickle)

data_list <- lapply(batch_data, function(x){
  x$data
  })
data <- do.call(rbind, data_list)

labels_list <- lapply(batch_data, function(x){
  x$labels
  })
labels <- do.call(c, labels_list)

x <- grayscale(data)
y <- labels

```


Train the autoencoder on images of horses:


```{r, fig.width=6, fig.height=1.5}

horse_indices <- which(labels == 7)
horse_x = x[horse_indices,]
print(dim(horse_x)) 



par(mfrow=c(1,5), mar = rep(1, 4))
num_examples<- 5

for(i in 1:num_examples){
  horse_img <- matrix(horse_x[i,], byrow=T, nrow=32)
  image(horse_img, 
      axes = FALSE, col = grey(seq(0, 1, length = 256)))
  
}


```



```{r}
input_dim <- dim(horse_x)[2]
hidden_dim <- 100
ae <- Autoencoder$new(input_dim, hidden_dim)
ae$train(horse_x)
```



```{r}
test_data <- unpickle('./cifar-10-batches-py/test_batch')
test_x <- grayscale(test_data[['data']])
test_labels <- test_data[['labels']]
encodings <- ae$classify(test_x, test_labels)
```



```{r,fig.height=10, fig.width=3}
par(mfrow=c(10,2), mar = rep(1, 4))

for(i in 1:20){
  org_img <- test_x[i,]
  image(matrix(org_img, byrow=T , nrow=32), 
      axes = FALSE, col = grey(seq(0, 1, length = 256)))
  
  encode_img <- ae$decode(matrix(encodings[i,], nrow=1, byrow=T))
  image(encode_img, 
      axes = FALSE, col = grey(seq(0, 1, length = 256)))

}

```

