---
title: "Machine Learning with TensorFlow(R version)"
output: github_document
---



[This](https://github.com/haven-jeon/TensorFlow-Book-R) is the unofficial code repository for [Machine Learning with TensorFlow](http://www.tensorflowbook.com/) with **R**.


This repository is for practicing [R tensorflow](https://cran.r-project.org/package=tensorflow) modeling exercises. I'm personally writing this code for me to know that there are some areas where you can get the benefits of R, and that the code in the book may contain partially improved or experimented code. (example: [CNN model view](https://github.com/haven-jeon/TensorFlow-Book-R/blob/master/ch09_cnn/Concept04_cifar.md) ) 


# TODO

- make full book example code with R.
- make use of `R Reference Class` for code reusablilty.  
- adding GAN code.


# Requirement 

- [TensorFlow](https://www.tensorflow.org/) (>= 1.0)
- [Python](https://www.python.org/) (>= 3.4)
- [tensorflow](https://cran.r-project.org/package=tensorflow) (>= 0.7) 
- [reticulate](https://cran.r-project.org/package=reticulate) (>= 0.7)

# Summary

## [Chapter 2](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch02_basics) - TensorFlow Basics

- **Concept 1**: [Defining tensors](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch02_basics/Concept01_defining_tensors.md)
- **Concept 2**: [Evaluating ops](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch02_basics/Concept02_evaluating_ops.md)
- **Concept 3**: [Interactive session](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch02_basics/Concept03_interactive_session.md)
- **Concept 4**: [Session loggings](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch02_basics/Concept04_session_logging.md)
- **Concept 5**: [Variables](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch02_basics/Concept05_variables.md)
- **Concept 6**: [Saving variables](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch02_basics/Concept06_saving_variables.md)
- **Concept 7**: [Loading variables](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch02_basics/Concept07_loading_variables.md)
- **Concept 8**: [TensorBoard](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch02_basics/Concept08_TensorBoard.md)

## [Chapter 3](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch03_regression) - Regression

- **Concept 1**: [Linear regression](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch03_regression/Concept01_linear_regression.md)
- **Concept 2**: [Polynomial regression](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch03_regression/Concept02_poly_regression.md)
- **Concept 3**: [Regularization](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch03_regression/Concept03_regularization.md)

## [Chapter 4](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch04_classification) - Classification

- **Concept 1**: [Linear regression for classification](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch04_classification/Concept01_linear_regression_classification.md)
- **Concept 2**: [Logistic regression](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch04_classification/Concept02_logistic.md)
- **Concept 3**: [2D Logistic regression](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch04_classification/Concept03_logistic2d.md)
- **Concept 4**: [Softmax classification](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch04_classification/Concept04_softmax.md)

## [Chapter 5](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch05_clustering) - Clustering (_working_)

- **Concept 1**: Clustering
- **Concept 2**: Segmentation
- **Concept 3**: Self-organizing map

## [Chapter 6](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch06_hmm) - Hidden markov models

- **Concept 1**: [Forward algorithm](https://github.com/haven-jeon/TensorFlow-Book-R/blob/master/ch06_hmm/Concept01_forward.md)
- **Concept 2**: [Viterbi decode](https://github.com/haven-jeon/TensorFlow-Book-R/blob/master/ch06_hmm/Concept02_hmm.md)


## [Chapter 7](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch07_autoencoder) - Autoencoders 

- **Concept 1**: [Autoencoder](https://github.com/haven-jeon/TensorFlow-Book-R/blob/master/ch07_autoencoder/Concept01_autoencoder.md)
- **Concept 2**: [Applying an autoencoder to images](https://github.com/haven-jeon/TensorFlow-Book-R/blob/master/ch07_autoencoder/Concept02_autoencoder_with_imgs.md)
- **Concept 3**: [Denoising autoencoder](https://github.com/haven-jeon/TensorFlow-Book-R/blob/master/ch07_autoencoder/Concept03_denoising.md)

## [Chapter 8](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch08_rl) - Reinforcement learning (_working_)

- **Concept 1**: Reinforcement learning

## [Chapter 9](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch09_cnn) - Convolutional Neural Networks

- **Concept 1**: [Using CIFAR-10 dataset](https://github.com/haven-jeon/TensorFlow-Book-R/blob/master/ch09_cnn/Concept01_cifar.md)
- **Concept 2**: [Convolutions](https://github.com/haven-jeon/TensorFlow-Book-R/blob/master/ch09_cnn/Concept02_convolution.md)
- **Concept 3**: [Convolutional neural network](https://github.com/haven-jeon/TensorFlow-Book-R/blob/master/ch09_cnn/Concept03_cnn.md)
- **Concept 4**: [Convolutional neural network model debugging(2)](https://github.com/haven-jeon/TensorFlow-Book-R/blob/master/ch09_cnn/Concept04_cifar.md), **Newly added**

## [Chapter 10](https://github.com/haven-jeon/TensorFlow-Book-R/tree/master/ch10_rnn) - Recurrent Neural Network(_working_)

- **Concept 1**: Loading timeseries data
- **Concept 2**: Recurrent neural networks
- **Concept 3**: Applying RNN to real-world data for timeseries prediction

