---
title: "Ch 02: Concept 06"
output: github_document
---

# Saving variables


Create an interactive session and initialize a variable:
```{r}
library(tensorflow)
sess <- tf$InteractiveSession()

raw_data <- c(1., 2., 8., -1., 0., 5.5, 6., 13)
spikes <- tf$Variable(rep(FALSE, length(raw_data)), name='spikes')
spikes$initializer$run()
```


The saver op will enable saving and restoring:
```{r}
saver <- tf$train$Saver()
```


Loop through the data and update the spike variable when there is a significant increase:
```{r}
for(i in 2:length(raw_data)){
    if(raw_data[i] - raw_data[i-1] > 5){
        spikes_val <- spikes$eval()
        spikes_val[i] <- TRUE
        updater <- tf$assign(spikes, spikes_val)
        updater$eval()
    }
}
g <- tf$get_default_graph()
for(n in g$get_operations())
  print(n$name)
```

Now, save your variable to disk!
```{r}
save_path <- saver$save(sess, "./spikes.ckpt")
print(paste("spikes data saved in file:" , save_path))
```


spikes data saved in file: spikes.ckpt

Adieu:

```{r}
sess$close()
```

